### PR TITLE
fix: When tool type cannot be determined, use DynamicJsonForm

### LINKED ISSUE #281: Cannot pass array inputs correctly (`type: array` results in string)
**Description:**  
When using a tool input schema with a field of `type: array` (e.g., `["string"]`), the inspector renders the input as a text field, and the value is passed as a single string rather than a proper JSON array. This causes schema validation to fail on the receiving server.

**To Reproduce:**  
1. Define a tool with an `inputSchema` that includes an `array` of strings (e.g., `type: ["array", "null"]`, `items: { "type": "string" }`)  
2. Attempt to invoke the tool from the inspector  
3. Observe the input is passed as a string instead of a list (e.g., `"["a", "b"]"` instead of `["a", "b"]`)

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "tags": {
      "type": ["array", "null"],
      "items": {
        "type": "string"
      },
      "description": "Optional list of tags."
    }
  },
  "required": []
}
```

**Expected behavior:**  
Inspector should recognize array types and provide UI to input a list, or at least pass a properly structured array to the backend.

### PR DESCRIPTION
**Pull request by max-stytch**
Fixes #281 

## Motivation and Context

Currently, when the `ToolsTab` cannot determine the type of a property (for example... if it a union type or something similarly complex) it defaults to a String input. This is rarely the correct choice - leading to bugs like #281 and #234.

The `DynamicJsonForm` component is waaaay nicer - and lets the caller set the exact value of the property - whether it is an object, array, or some other primitive type. Falling back to the JsonForm when we don't know how to interpret the type is nice, and feels like a reasonable solution compared to supporting arbitrarily complex nested JSON schema attributes.

## How Has This Been Tested?

Tested against #281 by creating a MCP Tool that takes in a nullable array of strings:
```typescript
        server.tool("arrayTest", {arr: z.nullable(z.array(z.string()))}, async ({arr}) => {
            console.log(arr);
            return {content: [{type: "text", text: `Success!`}]};
        })
```

This tool's schema is an `{anyOf:[...]}` and is missing the top level `prop.type` key.

I validated that the tool could be invoked using the new UI.

#### As Null
image
 
#### As Array
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [ ] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [ ] My code follows the repository's style guidelines
- [ ] New and existing tests pass locally
- [ ] I have added appropriate error handling
- [ ] I have added or updated documentation as needed

### CODE REVIEW

File: client/src/components/DynamicJsonForm.tsx [hunk 1]
```diff
@@ -36,15 +36,17 @@ interface DynamicJsonFormProps {
   value: JsonValue;
   onChange: (value: JsonValue) => void;
   maxDepth?: number;
+  onlyJSON?: boolean;
```
Comment (max-stytch) [inline client/src/components/DynamicJsonForm.tsx]: When using the DynamicJSONForm as a fallback value, we won't have a full-featured schema and the Form view doesn't work. Added a new bool to disable the form view - open to feedback/ alternative approaches

File: client/src/components/ToolsTab.tsx [hunk 2]
```diff
@@ -40,7 +40,13 @@ const ToolsTab = ({
...
   const [params, setParams] = useState<Record<string, unknown>>({});
   useEffect(() => {
-    setParams({});
+    const params = Object.entries(
+      selectedTool?.inputSchema.properties ?? [],
+    ).map(([key, value]) => [
+      key,
+      generateDefaultValue(value as JsonSchemaType),
+    ]);
+    setParams(Object.fromEntries(params));
```
Comment (max-stytch) [inline client/src/components/ToolsTab.tsx:52]: This fixes a separate bug where all params are initialized to `undefined`, which causes errors if someone hits `Run Tool` immediately and never interacts with the input.

**Comment by cliffhall** [comment]
Hi @max-stytch!

I love this take, particularly disabling the form if we can't display it.

But recently I've been wondering if the form view isn't just a fools errand, at least with the current approach. It only works in the simplest of cases. We could possibly explore the use of libraries like [react-jsonschema-form](https://www.npmjs.com/package/react-jsonschema-form) and [@jsonforms/react](https://www.npmjs.com/package/@jsonforms/react) to make the form more reliably match the schema, but I'm not sure how much effort it would take and if it would ever be adequate.

Even with this PR, trying to determine if we can properly create the form or if we should disable it is a problem in and of itself. 

For instance, in order to test it, I pointed to my [puzzlebox](https://github.com/cliffhall/puzzlebox/) server, whose `add_puzzle` tool wants a schema like this:
Screenshot 2025-04-11 at 1 58 42 PM

The record in the `states` field is problematic for the form, but your PR still shows it.
Screenshot 2025-04-11 at 1 49 28 PM

And as ever, if I go to the JSON input and add the data...
Screenshot 2025-04-11 at 1 50 51 PM

And then go back to the form, it can't display it properly either. 
Screenshot 2025-04-11 at 1 51 28 PM

Thoughts?

**Comment by max-stytch** [comment]
> But recently I've been wondering if the form view isn't just a fools errand, at least with the current approach. It only works in the simplest of cases. We could possibly explore the use of libraries like [react-jsonschema-form](https://www.npmjs.com/package/react-jsonschema-form) and [@jsonforms/react](https://www.npmjs.com/package/@jsonforms/react) to make the form more reliably match the schema, but I'm not sure how much effort it would take and if it would ever be adequate.

I tend to agree - this is a developer tool for power users, and being able to drop down into raw JSON is very nice for that audience. Building a UI around _all_ JSON schema features - including things like remote schema references - seems difficult. 

I think the form view is very nice for a top-level flat object with simple keys, but that is probably the exception rather than the rule. Perhaps instead of a `onlyJSON` boolean input, I enhance the DynamicJsonForm component to disable the Form when the schema is too complex?

**Comment by olaservo** [comment]
Agree with the comments here that the form UI has limited utility and I know I've spent a decent amount of time fighting with it.  Re: 
> Perhaps instead of a onlyJSON boolean input, I enhance the DynamicJsonForm component to disable the Form when the schema is too complex?

Are you thinking that 'too complex' would be anything beyond strings and numbers, for example?

**Comment by cliffhall** [comment]
>  Perhaps instead of a onlyJSON boolean input, I enhance the DynamicJsonForm component to disable the Form when the schema is too complex?

Top level properties of the simplest types? I suppose that would be OK for tools that hit basic APIs. Probably a lot of those.

**Comment by max-stytch** [comment]
> anything beyond strings and numbers, for example?

> Top level properties of the simplest types?

Yep - that's what I was thinking. Removed support for arrays and nested objects in https://github.com/modelcontextprotocol/inspector/pull/284/commits/3e95d9d42abe919d63673c42822449301616480b.

**Comment by cliffhall** [comment]
Nice one, @max-stytch! Tried it with simple and complex cases, and it did the right thing. 

### Simple schema
Screenshot 2025-04-16 at 5 08 09 PM

### Complex schema
Screenshot 2025-04-16 at 5 06 51 PM

**Review by cliffhall — APPROVED** [review]
Code, build, test, lint, all look good. Manually tested with simple and complex cases. LGTM! 👍
