### PR TITLE
fix: detect 401 errors from `StreamableHTTP` transport in client

### LINKED ISSUE #982: v0.18.0 in Streamable HTTP direct failed on OAuth 401
**Inspector Version**

Stopped working in **v0.18.0**

Confirmed working in **v0.17.5**

**Describe the bug**

I try to connect to an MCP server that requires OAuth. Transport type is **Streamable HTTP**, connection type is **Direct**.

MCP inspector in v0.18.0 performs a single `POST` request (excluding the `OPTIONS` one), to the given URL, to which the MCP server replies with
 - **status code**: 401
 - **header `www-authenticate`**: `Bearer error="invalid_token", error_description="Authentication required", resource_metadata="https://redacted.example.com/.well-known/oauth-protected-resource/mcp"`
 - **body**: `{"error": "invalid_token", "error_description": "Authentication required"}`

The following error is displayed on the console:
```
Failed to connect directly to MCP Server at: https://redacted.example.com/mcp: Error: Streamable HTTP error: Error POSTing to endpoint: {"error": "invalid_token", "error_description": "Authentication required"}
```

**To Reproduce**

1. Go to **MCP inspector**
2. Set transport type to **Streamable HTTP**
3. Set the URL
4. Set connection type to **Direct**
5. Click on **Connect**
6. See error in web console

**Additional info**

The “step by step” and “quick auth flow” modes accessible by opening the auth settings both still work properly in v0.18.0 for the same MCP server.

**Environment (please complete the following information):**

- I am using the docker image
- Browser: tested with both Chrome and Firefox

### PR DESCRIPTION
**Pull request by thinhtpt-dev**
## Summary

Fix issue OAuth Flow was not triggered when using `StreamableHTTP` with `Direct` connection type.

> **Note:** Inspector V2 is under development to address architectural and UX improvements. During this time, V1 contributions should focus on **bug fixes and MCP spec compliance**. See [CONTRIBUTING.md](../CONTRIBUTING.md) for more details.

## Type of Change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Test updates
- [ ] Build/CI improvements

## Changes Made

Added `StreamableHTTPError` handling to `is401Error()` so 401 responses from the Streamable HTTP transport now trigger the existing auth-retry flow, keeping OAuth re-auth logic consistent across transport types.

## Related Issues

Fixes #982 and #960

## Testing

- [X] Tested in UI mode
- [ ] Tested in CLI mode
- [ ] Tested with STDIO transport
- [ ] Tested with SSE transport
- [X] Tested with Streamable HTTP transport
- [ ] Added/updated automated tests
- [ ] Manual testing performed

### Test Results and/or Instructions

**How to test this fix:**
1. Set up an MCP server with OAuth protection that returns a WWW-Authenticate header on 401
2. Start the Inspector and select "Streamable HTTP" transport
3. Enter the OAuth-protected MCP server URL
4. Select "Direct" option in Connection Type
5. Click Connect
6. Expected (with fix): OAuth flow is triggered - user is redirected to Authorization page
7. Before fix: Shows "Connection Error - Check if your MCP server is running and proxy token is correct"

## Checklist

- [X] Code follows the style guidelines (ran `npm run prettier-fix`)
- [X] Self-review completed
- [X] Code is commented where necessary
- [ ] Documentation updated (README, comments, etc.)

### CODE REVIEW

**Comment by thinhtpt-dev** [comment]
Hi @cliffhall, can you help us take a look this pull request? Thank you.

**Comment by cliffhall** [comment]
> Hi @cliffhall, can you help us take a look this pull request? Thank you.

Hi @thinhtpt-dev! Thanks for this, and it does seem to solve the problem, but for Direct mode only. Still trying to figure out where Via Proxy is dropping the ball and hoping to get a single PR to fix it.

File: client/src/lib/hooks/useConnection.ts [hunk 1]
```diff
@@ -358,6 +359,7 @@ export function useConnection({
   const is401Error = (error: unknown): boolean => {
     return (
       (error instanceof SseError && error.code === 401) ||
+      (error instanceof StreamableHTTPError && error.code === 401) ||
       (error instanceof Error && error.message.includes("401")) ||
       (error instanceof Error && error.message.includes("Unauthorized"))
     );
```
Comment (cliffhall) [inline client/src/lib/hooks/useConnection.ts]:
```suggestion
  const is401Error = (error: unknown): boolean => {
    return (
      (error instanceof SseError && error.code === 401) ||
      (error instanceof StreamableHTTPError && error.code === 401) ||
      (error instanceof Error && error.message.includes("401")) ||
      (error instanceof Error && error.message.includes("Unauthorized")) ||
      (error instanceof Error && error.message.includes("Missing Authorization header"))
    );
```

Comment (cliffhall) [reply client/src/lib/hooks/useConnection.ts]: I verified that this changes fixes it for Direct mode. Adding this _extra check_ fixes the issue for Via Proxy mode.

```typescript
(error instanceof Error && error.message.includes("Missing Authorization header"))
```

**Review by cliffhall — DISMISSED** [review]

File: client/src/lib/hooks/useConnection.ts [hunk 2]
```diff
@@ -358,8 +359,15 @@ export function useConnection({
...
+      (error instanceof StreamableHTTPError && error.code === 401) ||
       (error instanceof Error && error.message.includes("401")) ||
-      (error instanceof Error && error.message.includes("Unauthorized"))
+  const is401Error = (error: unknown): boolean => {
+    return (
+      (error instanceof SseError && error.code === 401) ||
+      (error instanceof StreamableHTTPError && error.code === 401) ||
+      (error instanceof Error && error.message.includes("401")) ||
+      (error instanceof Error && error.message.includes("Unauthorized")) ||
+      (error instanceof Error && error.message.includes("Missing Authorization header"))
```
Comment (cliffhall) [inline client/src/lib/hooks/useConnection.ts]:
```suggestion
      (error instanceof Error &&
        error.message.includes("Missing Authorization header"))
```

Comment (cliffhall) [reply client/src/lib/hooks/useConnection.ts]: Should fix prettier

**Review by cliffhall — COMMENTED** [review]
Trying to fix botched patch

**Comment by evalstate** [comment]
Tested against OAuth Servers in both modes, LGTM.

**Review by evalstate — APPROVED** [review]

**Comment by jacopoc** [comment]
@cliffhall I have also tested the latest changes with https://example-server.modelcontextprotocol.io/mcp and I am getting different results.

In particular, **Proxy** mode works fine, whereas in **Direct** mode, after the redirection and successful user authentication/authorization, the connection fails with the following generic error displayed under the Connect button:
`Connection Error - Check if your MCP server is running and proxy token is correct`

I've noticed, but I don't know if it is relevant, that in the Developers tools of the browser the following request returns a **400 Bad Request** error:
```
Request URL: https://example-server.modelcontextprotocol.io/mcp
Request Method: POST
Request body: {method: "notifications/initialized", jsonrpc: "2.0"}
```

**Comment by jacopoc** [comment]
@cliffhall Thank you, I confirm it works with the test server. I am going to dig deeper to figure out the reason Proxy mode fails to work with my Keycloak instance and let you know if I find anything relevant for this project.
