### PR TITLE
fix: enhance OAuth token handling in useConnection hook to prevent infinite auth loops

### LINKED ISSUE #829: Authentication Header not coming through with TypeScript SDK 1.18.2
**Inspector Version**

0.16.8 (latest)

**Describe the bug**

Attempt to connect to an MCP server which uses `@modelcontextprotocol/sdk@1.18.2` and reports 401 upon unauthorized connection (like [this one](https://github.com/epicweb-dev/epic-me-mcp)).

This triggers the OAuth flow as expected, however, the Inspector doesn't appear to be sending the auth token in the authorization header, leading to an infinite loop:

Image

My server logs:

```
{ authorization: null }
 (x6)
{ authorization: null }
 (x7)
{ authorization: 'Bearer' }

OAuth error response: 401 invalid_token - Missing or invalid access token

{ authorization: null }

{ authorization: null }
 (x2)
{ authorization: null }
 (x3)
{ authorization: null }
 (x4)
```

The inspector logs:

```
New StreamableHttp connection request
Query parameters: {"url":"http://localhost:8877/mcp","transportType":"streamable-http"}
Created StreamableHttp client transport
Client <-> Proxy  sessionId: cbf4e713-924d-4e49-9076-858c553d47d5
Error from MCP server: Error: Error POSTing to endpoint (HTTP 401): {"error":"invalid_token","error_description":"Missing or invalid access token"}
    at StreamableHTTPClientTransport.send (file:///Users/kentcdodds/code/epic-web/epic-me-mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/client/streamableHttp.js:284:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
New StreamableHttp connection request
Query parameters: {"url":"http://localhost:8877/mcp","transportType":"streamable-http"}
Created StreamableHttp client transport
Client <-> Proxy  sessionId: 61de52e2-359a-4178-9081-c0ed74d79f1c
Error from MCP server: Error: Error POSTing to endpoint (HTTP 401): {"error":"invalid_token","error_description":"Missing or invalid access token"}
    at StreamableHTTPClientTransport.send (file:///Users/kentcdodds/code/epic-web/epic-me-mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/client/streamableHttp.js:284:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
New StreamableHttp connection request
Query parameters: {"url":"http://localhost:8877/mcp","transportType":"streamable-http"}
Created StreamableHttp client transport
Client <-> Proxy  sessionId: de6594fe-e171-4841-9ede-2bcbba107722
Error from MCP server: Error: Error POSTing to endpoint (HTTP 401): {"error":"invalid_token","error_description":"Missing or invalid access token"}
    at StreamableHTTPClientTransport.send (file:///Users/kentcdodds/code/epic-web/epic-me-mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/client/streamableHttp.js:284:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**To Reproduce**

```
git clone https://github.com/epicweb-dev/epic-me-mcp.git
cd epic-me-mcp
git checkout f64a979cb5ffbbf4554d4399e045da6aa540034c
npm install
npm run dev
```

In another tab:

```
npm run inspect
```

1. Click Connect
2. The OAuth flow will complete (using [just-in-time auth](https://www.epicai.pro/user-friendly-just-in-time-auth-with-mcp-hd9hw) so you won't see it pop up... I have reproduced the same issue in another server that uses more traditional auth so I know this isn't the issue)
3. The app doesn't show you there's anything wrong, but behind the scenes it's DOS-ing the server 😅

**Expected behavior**

Send the authorization header it retrieved from the OAuth flow.

The inspector should probably detect when there's an infinite loop like this and prevent it too?

**Environment (please complete the following information):**

- OS: macOS
- Browser Brave

**Additional context**

I haven't had time to dig any deeper into this. Seems odd to me. It's possible this is an issue in the SDK, but I've verified things are working as expected with other clients like [nanobot.ai](https://www.nanobot.ai/) so I think there's an issue with the Inspector.

### PR DESCRIPTION
**Pull request by kentcdodds**
Fix OAuth token injection when default `"Bearer "` header is present, preventing infinite auth loops

Closes #829

## Motivation and Context

This change fixes a critical authentication bug that caused infinite OAuth loops in the inspector. The issue occurred when users had the default `customHeaders` configuration with an empty "Bearer " placeholder header. The authentication logic would send "Bearer " (without an actual token) to the server, which would return a 401 error, triggering OAuth flow, but the same empty header would be sent again, creating an infinite loop.

The root cause was that the OAuth token injection logic only triggered when `finalHeaders.length === 0`, but the default configuration always included a placeholder header `{ name: "Authorization", value: "Bearer ", enabled: true }`, so the condition was never met.

## How Has This Been Tested?

- Added a specific regression test case `"replaces empty Bearer token placeholder with OAuth token"` that verifies the fix
- All existing tests in the useConnection test suite pass (36/36 tests)
- The test verifies that when a default "Bearer " header is present, it gets replaced with the actual OAuth token "Bearer mock-token"

## Breaking Changes

None. This is a bug fix that preserves existing behavior while fixing the authentication issue.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [x] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have added or updated documentation as needed

## Additional context

I'm actually open to instead changing the default header to exclude the empty `Bearer `. Arguably that's a more appropriate fix. But I figured there's a reason that default was added so I decided to just handle it gracefully.

### CODE REVIEW

**Comment by kentcdodds** [comment]
I'm much happier with this 👍

File: client/src/App.tsx [hunk 1]
```diff
@@ -162,14 +162,8 @@ const App = () => {
       return migrateFromLegacyAuth(legacyToken, legacyHeaderName);
     }
 
-    // Default to Authorization: Bearer as the most common case
-    return [
-      {
-        name: "Authorization",
-        value: "Bearer ",
-        enabled: true,
```
Comment (cliffhall) [inline client/src/App.tsx:172]: Would an better way to do this be to leave it, but disable it? So for the common use case of adding an authorization header they just enable it and add their token, but otherwise it's just ignored when headers are sent? Makes it handy, but removes the footgun. With the robust checking you've added above in useConnection, we can be confident in the proper behavior should they switch it on but fail to add a token.

**Review by cliffhall — CHANGES_REQUESTED** [review]
@kentcdodds Left a comment that I think makes sense, leaving the handiness of the predefined header, but not having it enabled by default. Requesting the change, but will approve if you think that's still problematic.

File: client/src/App.tsx (hunk 1 above)
Comment (kentcdodds) [reply client/src/App.tsx:172]: I wonder if there's a situation where someone would want to test the lack of an auth header without actually removing the auth token from their client 🤔

Disabling the Auth header would be how I would want to do that.

Comment (olaservo) [reply client/src/App.tsx:172]: So instead of removing this chunk, should we just set the default to `enabled: false`?

Comment (kentcdodds) [reply client/src/App.tsx:172]: I'm a little confused why this chunk was added in the first place.

Comment (kentcdodds) [reply client/src/App.tsx:172]: I guess for myself, I always just use the auth flow that's built into the inspector. But I suppose some people have something more complicated and they have to get an auth token through some other means. But to me, that seems like more of an edge case. And a person in that situation would know how to add a new header called authorization with a bearer prefix. I don't think that they need our help to do that.

Comment (olaservo) [reply client/src/App.tsx:172]: Just speaking for myself and a few others I've seen chime in on the original feature request - I've worked with quite a few servers that don't support OAuth and where I need to pass something like a Personal Access Token through the authorization header, so this UI option seems more intuitive for that scenario?

Comment (kentcdodds) [reply client/src/App.tsx:172]: I'm happy to go whatever direction you all want with this. Just seems odd to me to have the headers include an invalid auth header (even if it's disabled) when it's quite easy to add and then it even saves to localstorage once you have 🤷‍♂️

Additionally, I do think this is a much less common case so we are increasing confusion for more folks to make things a tiny bit easier for fewer folks 🤔

Comment (cliffhall) [reply client/src/App.tsx:172]: @kentcdodds can we just leave it and turn it off by default? The point is that it saves the person who needs to add a bearer token some typing and possible fat-finger errors. I don't see how it's really going to sow confusion. Anyone monkeying with headers will know the bearer token header pattern, and if they don't, they'll probably just leave it turned off. If they do just turn it on and mash connect, they'll get a toast about it being incomplete and see the error of their ways. It's not a footgun, it's just a convenience.

Comment (kentcdodds) [reply client/src/App.tsx:172]: Sounds good. I changed it though so it does not automatically replace an empty auth header to reduce "magic." People will see the toast and go disable the header. I'm happy with that :)

File: client/src/lib/hooks/useConnection.ts [hunk 2]
```diff
@@ -400,11 +400,37 @@ export function useConnection({
...
+      // Check for empty Authorization headers and show validation error
+      const hasEmptyAuthHeader = finalHeaders.some(
+        (header) => header.enabled && isEmptyAuthHeader(header),
+      );
+
+      if (hasEmptyAuthHeader) {
+        toast({
+          title: "Invalid Authorization Header",
+          description:
+            "Authorization header is enabled but empty. Please add a token or disable the header. It will be added automatically.",
```
Comment (cliffhall) [inline client/src/lib/hooks/useConnection.ts]:
```suggestion
            "Authorization header is enabled but empty. Please add a token or disable the header.",
```
