### PR TITLE
Fix ESLint rules-of-hooks warnings

### LINKED ISSUE #217: Fix ESlint rules-of-hooks warnings in App.tsx
**Describe the bug**
Although [this previous PR](https://github.com/modelcontextprotocol/inspector/pull/151) was intended to fix ESlint warnings about rules of hooks, IDE continues to highlight it in the current App.tsx

**To Reproduce**
1. cd to `inspector/client`
2. run `eslint`

Image

**Expected behavior**
No warnings about React Hooks being called conditionally. 

**Additional context**
Raised in response to [this PR](https://github.com/modelcontextprotocol/inspector/pull/204#pullrequestreview-2722661863) which was going to incidentally suppress rules-of-hooks warnings. Instead of suppressing the warning, I intend to fix the problem.

### PR DESCRIPTION
**Pull request by cliffhall**
This fixes https://github.com/modelcontextprotocol/inspector/issues/217 about the linter's warning that Hooks must be run in order each time.

* In App.tsx
  - move the conditional that returns suspense if the path is oauth/callback to the end of the component after all hooks, rendering either suspense or the normal component.
  - move `handleApproveSampling` and `handleRejectSampling` constants down below all the hooks for clarity. There are a lot of hooks so finding the end of them is a scroll, and these function constants aren't referenced until the rendering section below anyway.
  - In the useEffect used to auto-connect if serverUrl is provided in URL params, add the `connectMcpServer` method as a dependency, quieting the ESLint complaint about it.
  - Prettier fixed indenting at the end, so it looks like a bigger change than it actually is.

## Motivation and Context

Software correctness.

## How Has This Been Tested?

1. cd to `inspector/client`
2. run `eslint`

### Previous output
Screenshot 2025-03-27 at 4 34 54 PM

### After fix (other warnings still exist, but are out of scope for this fix)
Screenshot 2025-03-27 at 4 36 21 PM

* All normal Inspector functionality tested with normal SSE and STDIO servers as usual.
* The conditional path that leads to suspense was when the path was `oauth/callback`, tested with this minimal [GitHub OAuth MCP server](https://github.com/dend/github-oauth-mcp).
oauth

## Breaking Changes

Nope. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [x] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [ ] I have added appropriate error handling
- [ ] I have added or updated documentation as needed

## Additional context

Fixes #217 which was raised in response to [this PR](https://github.com/modelcontextprotocol/inspector/pull/204#pullrequestreview-2722661863) which was going to incidentally suppress rules-of-hooks warnings. I wanted to fix the problem instead.

### CODE REVIEW

**Review by olaservo — DISMISSED** [review]
Thanks for testing that the Oauth callback is still working!  🥇

File: client/src/App.tsx [hunk 1]
```diff
@@ -425,251 +415,263 @@ const App = () => {
...
+  if (window.location.pathname === "/oauth/callback") {
+    const OAuthCallback = React.lazy(
+      () => import("./components/OAuthCallback"),
+    );
+    return (
+      <Suspense fallback={<div>Loading...</div>}>
+        <OAuthCallback />
+      </Suspense>
+    );
+  } else {
```
Comment (pulkitsharma07) [inline client/src/App.tsx]: this `else` is redundant here because of the `return` above

Comment (cliffhall) [reply client/src/App.tsx]: Not really. It could be that the diff view was confusing. This is the structure we're looking at:

Screenshot 2025-03-28 at 3 16 48 PM

The `return` in the block above the `} else {` only executes if that condition was met, otherwise we return the  component in the block after the `} else {`.

Comment (pulkitsharma07) [reply client/src/App.tsx]: Wouldn't this also work:

```js
if(condition) {
 return (...)
}
return (...)
```

instead of 
```js
if(condition) {
 return (...)
} else {
 return (...)
}
```

Comment (cliffhall) [reply client/src/App.tsx]: It would, but the else makes it clear that what's returned from the component is either or. It's not less performant or incorrect. If I were to revisit, I'd make those blocks functions and have a single return statement at the end for clarity. Two returns is an anti-pattern.

Comment (pulkitsharma07) [reply client/src/App.tsx]: Alright 👍, I was just thinking that removing that `else`  would help in reducing the indentation or the diff size of the entire block.

Comment (cliffhall) [reply client/src/App.tsx]: True that. Easier to approve. I'll do that.

Comment (cliffhall) [reply client/src/App.tsx]: @pulkitsharma07 Ok, that did make the diff much shorter, so it should be easier to be confident about the changes.

**Review by pulkitsharma07 — APPROVED** [review]

**Review by olaservo — APPROVED** [review]
